<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NxZTCM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NxZTCM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2NxZTCM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2NxZTCM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container2NxZTCM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '2NxZTCM',
    'container.build_id' => '7813dbec',
    'container.build_time' => 1558911495,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NxZTCM');
